tasks:
  - init: yarn start
    command: |
      gp ports await 8065
      yarn setup
ports:
  - port: 8065
    onOpen: open-browser
    visibility: public
  - port: 8005
    onOpen: open-browser
    visibility: public
