tasks:
  - name: Install & Setup
    init: nvm install lts/hydrogen && nvm use lts/hydrogen
    command: yarn install
ports:
  - port: 8065
    onOpen: open-browser
    visibility: public
  - port: 8005
    onOpen: open-browser
    visibility: public
