tasks:
  - name: Install & Setup
    init: nvm install lts/hydrogen && nvm use lts/hydrogen
    command: yarn install
    openMode: "split-left"
  - name: Start
    init: sleep 65 && nvm use lts/hydrogen
    command: cd rooster && yarn install && yarn start
    openMode: "split-right"
ports:
  - port: 8065
    onOpen: open-browser
    visibility: public
  - port: 8005
    onOpen: open-browser
    visibility: public
